default_index:
  path:     /
  defaults: { _controller: AppBundle:Default:index }
  methods: GET

default_test:
  path:     /testadduser
  defaults: { _controller: AppBundle:Default:testadduser }
  methods: GET