# En routing.yml, el prefix de esta ruta es user/, y los path aquí sons a partir de este prefix.
# Por ejemplo, user_index si tiene un path /, la ruta final será:  task/
task_index:
  path:     /
  defaults: { _controller: AppBundle:Task:index }
  methods: GET

task_new:
  path:     /new
  defaults: { _controller: AppBundle:Task:new }
  methods: POST

task_edit:
  path:     /edit/{id}
  defaults: { _controller: AppBundle:Task:new, id:null }
  methods: POST

task_list:
  path:     /list
  defaults: { _controller: AppBundle:Task:list}
  methods: POST

task_detail:
  path:     /detail/{id}
  defaults: { _controller: AppBundle:Task:detail}
  methods: POST

task_search:
  path:     /search/{search}
  defaults: { _controller: AppBundle:Task:search, search:null }
  methods: POST

task_remove:
  path:     /remove/{id}
  defaults: { _controller: AppBundle:Task:remove}
  methods: POST